### ISSUE TITLE
What about the license?

### ISSUE THREAD

**Issue by maly** [WestfW/4chipZ80#1]
Hello, I would like to use this construction as a demo construction in my book about building homebrew 8bit computers. Is it possible? What about the license terms? Is it MIT, or CC-BY, or GPL? Can you please specify it?

Thanks

Martin

**Comment by WestfW** [comment]
The EAGLE implementation of the design is OSHW, let's say CC-SA 4.0.  I'm not sure about the design itself; I guess it's not very protected.
The Fig-Forth port is still public domain.
The ATmega32 firmware, Z80 loader, BIOS, and other firmware, all belongs to someone else.  I don't think they've attached an explicit license.

I added a "License.txt"

**Comment by maly** [comment]
Thank you a lot!
